export type GradientKeys =
  | 'Omolon'
  | 'Farhan'
  | 'Purple'
  | 'Ibtesam'
  | 'Radioactive Heat'
  | 'The Sky And The Sea'
  | 'From Ice To Fire'
  | 'Blue & Orange'
  | 'Purple Dream'
  | 'Blu'
  | 'Summer Breeze'
  | 'Ver'
  | 'Ver Black'
  | 'Combi'
  | 'Anwar'
  | 'Bluelagoo'
  | 'Lunada'
  | 'Reaqua'
  | 'Mango'
  | 'Bupe'
  | 'Rea'
  | 'Windy'
  | 'Royal Blue'
  | 'Royal Blue + Petrol'
  | 'Copper'
  | 'Anamnisar'
  | 'Petrol'
  | 'Sky'
  | 'Sel'
  | 'Afternoon'
  | 'Skyline'
  | 'DIMIGO'
  | 'Purple Love'
  | 'Sexy Blue'
  | 'Blooker20'
  | 'Sea Blue'
  | 'Nimvelo'
  | 'Hazel'
  | 'Noon to Dusk'
  | 'YouTube'
  | 'Cool Brown'
  | 'Harmonic Energy'
  | 'Playing with Reds'
  | 'Sunny Days'
  | 'Green Beach'
  | 'Intuitive Purple'
  | 'Emerald Water'
  | 'Lemon Twist'
  | 'Monte Carlo'
  | 'Horizon'
  | 'Rose Water'
  | 'Frozen'
  | 'Mango Pulp'
  | 'Bloody Mary'
  | 'Aubergine'
  | 'Aqua Marine'
  | 'Sunrise'
  | 'Purple Paradise'
  | 'Stripe'
  | 'Sea Weed'
  | 'Pinky'
  | 'Cherry'
  | 'Mojito'
  | 'Juicy Orange'
  | 'Mirage'
  | 'Steel Gray'
  | 'Kashmir'
  | 'Electric Violet'
  | 'Venice Blue'
  | 'Bora Bora'
  | 'Moss'
  | 'Shroom Haze'
  | 'Mystic'
  | 'Midnight City'
  | 'Sea Blizz'
  | 'Opa'
  | 'Titanium'
  | 'Mantle'
  | 'Dracula'
  | 'Peach'
  | 'Moonrise'
  | 'Clouds'
  | 'Stellar'
  | 'Bourbon'
  | 'Calm Darya'
  | 'Influenza'
  | 'Shrimpy'
  | 'Army'
  | 'Miaka'
  | 'Pinot Noir'
  | 'Day Tripper'
  | 'Namn'
  | 'Blurry Beach'
  | 'Vasily'
  | 'A Lost Memory'
  | 'Petrichor'
  | 'Jonquil'
  | 'Sirius Tamed'
  | 'Kyoto'
  | 'Misty Meadow'
  | 'Aqualicious'
  | 'Moor'
  | 'Almost'
  | 'Forever Lost'
  | 'Winter'
  | 'Nelson'
  | 'Autumn'
  | 'Candy'
  | 'Reef'
  | 'The Strain'
  | 'Dirty Fog'
  | 'Earthly'
  | 'Virgin'
  | 'Ash'
  | 'Cherryblossoms'
  | 'Parklife'
  | 'Dance To Forget'
  | 'Starfall'
  | 'Red Mist'
  | 'Teal Love'
  | 'Neon Life'
  | 'Man of Steel'
  | 'Amethyst'
  | 'Cheer Up Emo Kid'
  | 'Shore'
  | 'Facebook Messenger'
  | 'SoundCloud'
  | 'Behongo'
  | 'ServQuick'
  | 'Friday'
  | 'Martini'
  | 'Metallic Toad'
  | 'Between The Clouds'
  | 'Crazy Orange I'
  | 'Hersheys'
  | 'Talking To Mice Elf'
  | 'Purple Bliss'
  | 'Predawn'
  | 'Endless River'
  | 'Pastel Orange at the Sun'
  | 'Twitch'
  | 'Atlas'
  | 'Instagram'
  | 'Flickr'
  | 'Vine'
  | 'Turquoise flow'
  | 'Portrait'
  | 'Virgin America'
  | 'Koko Caramel'
  | 'Fresh Turboscent'
  | 'Green to dark'
  | 'Ukraine'
  | 'Curiosity blue'
  | 'Dark Knight'
  | 'Piglet'
  | 'Lizard'
  | 'Sage Persuasion'
  | 'Between Night and Day'
  | 'Timber'
  | 'Passion'
  | 'Clear Sky'
  | 'Master Card'
  | 'Back To Earth'
  | 'Deep Purple'
  | 'Little Leaf'
  | 'Netflix'
  | 'Light Orange'
  | 'Green and Blue'
  | 'Poncho'
  | 'Back to the Future'
  | 'Blush'
  | 'Inbox'
  | 'Purplin'
  | 'Pale Wood'
  | 'Haikus'
  | 'Pizelex'
  | 'Joomla'
  | 'Christmas'
  | 'Minnesota Vikings'
  | 'Miami Dolphins'
  | 'Forest'
  | 'Nighthawk'
  | 'Superman'
  | 'Suzy'
  | 'Dark Skies'
  | 'Deep Space'
  | 'Decent'
  | 'Colors Of Sky'
  | 'Purple White'
  | 'Ali'
  | 'Alihossein'
  | 'Shahabi'
  | 'Red Ocean'
  | 'Tranquil'
  | 'Transfile'
  | 'Sylvia'
  | 'Sweet Morning'
  | 'Politics'
  | 'Bright Vault'
  | 'Solid Vault'
  | 'Sunset'
  | 'Grapefruit Sunset'
  | 'Deep Sea Space'
  | 'Dusk'
  | 'Minimal Red'
  | 'Royal'
  | 'Mauve'
  | 'Frost'
  | 'Lush'
  | 'Firewatch'
  | 'Sherbert'
  | 'Blood Red'
  | 'Sun on the Horizon'
  | 'IIIT Delhi'
  | 'Jupiter'
  | '50 Shades of Grey'
  | 'Dania'
  | 'Limeade'
  | 'Disco'
  | 'Love Couple'
  | 'Azure Pop'
  | 'Nepal'
  | 'Cosmic Fusion'
  | 'Snapchat'
  | "Ed's Sunset Gradient"
  | 'Brady Brady Fun Fun'
  | 'Black Rosé'
  | "80's Purple"
  | 'Radar'
  | 'Ibiza Sunset'
  | 'Dawn'
  | 'Mild'
  | 'Vice City'
  | 'Jaipur'
  | 'Jodhpur'
  | 'Cocoaa Ice'
  | 'EasyMed'
  | 'Rose Colored Lenses'
  | 'What lies Beyond'
  | 'Roseanna'
  | 'Honey Dew'
  | 'Under the Lake'
  | 'The Blue Lagoon'
  | 'Can You Feel The Love Tonight'
  | 'Very Blue'
  | 'Love and Liberty'
  | 'Orca'
  | 'Venice'
  | 'Pacific Dream'
  | 'Learning and Leading'
  | 'Celestial'
  | 'Purplepine'
  | 'Sha la la'
  | 'Mini'
  | 'Maldives'
  | 'Cinnamint'
  | 'Html'
  | 'Coal'
  | 'Sunkist'
  | 'Blue Skies'
  | 'Chitty Chitty Bang Bang'
  | 'Visions of Grandeur'
  | 'Crystal Clear'
  | 'Mello'
  | 'Compare Now'
  | 'Meridian'
  | 'Relay'
  | 'Alive'
  | 'Scooter'
  | 'Terminal'
  | 'Telegram'
  | 'Crimson Tide'
  | 'Socialive'
  | 'Subu'
  | 'Broken Hearts'
  | 'Kimoby Is The New Blue'
  | 'Dull'
  | 'Purpink'
  | 'Orange Coral'
  | 'Summer'
  | 'King Yna'
  | 'Velvet Sun'
  | 'Zinc'
  | 'Hydrogen'
  | 'Argon'
  | 'Lithium'
  | 'Digital Water'
  | 'Orange Fun'
  | 'Rainbow Blue'
  | 'Pink Flavour'
  | 'Sulphur'
  | 'Selenium'
  | 'Delicate'
  | 'Ohhappiness'
  | 'Lawrencium'
  | 'Relaxing red'
  | 'Taran Tado'
  | 'Bighead'
  | 'Sublime Vivid'
  | 'Sublime Light'
  | 'Pun Yeta'
  | 'Quepal'
  | 'Sand to Blue'
  | 'Wedding Day Blues'
  | 'Shifter'
  | 'Red Sunset'
  | 'Moon Purple'
  | 'Pure Lust'
  | 'Slight Ocean View'
  | 'eXpresso'
  | 'Shifty'
  | 'Vanusa'
  | 'Evening Night'
  | 'Magic'
  | 'Margo'
  | 'Blue Raspberry'
  | 'Citrus Peel'
  | 'Sin City Red'
  | 'Rastafari'
  | 'Summer Dog'
  | 'Wiretap'
  | 'Burning Orange'
  | 'Ultra Voilet'
  | 'By Design'
  | 'Kyoo Tah'
  | 'Kye Meh'
  | 'Kyoo Pal'
  | 'Metapolis'
  | 'Flare'
  | 'Witching Hour'
  | 'Azur Lane'
  | 'Neuromancer'
  | 'Harvey'
  | 'Amin'
  | 'Memariani'
  | 'Yoda'
  | 'Cool Sky'
  | 'Dark Ocean'
  | 'Evening Sunshine'
  | 'JShine'
  | 'Moonlit Asteroid'
  | 'MegaTron'
  | 'Cool Blues'
  | 'Piggy Pink'
  | 'Grade Grey'
  | 'Telko'
  | 'Zenta'
  | 'Electric Peacock'
  | 'Under Blue Green'
  | 'Lensod'
  | 'Newspaper'
  | 'Dark Blue Gradient'
  | 'Dark Blu Two'
  | 'Lemon Lime'
  | 'Beleko'
  | 'Mango Papaya'
  | 'Unicorn Rainbow'
  | 'Flame'
  | 'Blue Red'
  | 'Twitter'
  | 'Blooze'
  | 'Blue Slate'
  | 'Space Light Green'
  | 'Flower'
  | 'Elate The Euge'
  | 'Peach Sea'
  | 'Abbas'
  | 'Winter Woods'
  | 'Ameena'
  | 'Emerald Sea'
  | 'Bleem'
  | 'Coffee Gold'
  | 'Compass'
  | "Andreuzza's"
  | 'Moonwalker'
  | 'Whinehouse'
  | 'Hyper Blue'
  | 'Racker'
  | 'After the Rain'
  | 'Neon Green'
  | 'Dusty Grass'
  | 'Visual Blue';
